[workspace]
authors = ["Yiran Lu <yiranls@outlook.com>"]
channels = ["conda-forge"]
name = "paris-velo-meteo"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
ipykernel = ">=7.1.0,<8"
requests = ">=2.32.5,<3"
streamlit = ">=1.52.2,<2"
blas = { version = "*", build = "*openblas" }
pandas = ">=2.3.3,<3"
geopandas = ">=1.1.1,<2"
duckdb = ">=1.4.3,<2"
sqlalchemy = ">=2.0.45,<3"
beautifulsoup4 = ">=4.14.3,<5"
lxml = ">=6.0.2,<7"
streamlit-folium = ">=0.25.2,<0.26"
